config {
  type: "incremental",
  name: "dim_seasons",
  schema: "analytics",
  description: "Defines seasons.",
  uniqueKey: ["season_id"]
}

SELECT DISTINCT
    season as season_name,
    REPLACE(season, '/', '') AS season_id
FROM ${ref("clean_injuries_data")}
${
    when(incremental(),
    `
    WHERE NOT EXISTS (
        SELECT 1 
        FROM ${self()} t
        WHERE t.season_id = season_id
    )`)
}
