config {
  type: "incremental",
  name: "dim_matches",
  schema: "analytics",
  description: "Defines matches.",
  uniqueKey: ["game_id"]
}

SELECT
    DISTINCT game as game_id,
    season as season_id,
    week as game_week,
    date as match_date,
    league as league_id,
    home_team,
    away_team,
    venue as stadium,
    referee,
    attendance
FROM ${ref("timetable_status")}
${
  when(incremental(), 
  `
  WHERE NOT EXISTS (SELECT 1 FROM ${self()} WHERE game_id = game_id)
  `)
}
