config {
    type: "incremental",
    name: "fact_player_season",
    description: "Fact table for every player season",
    uniqueKey: ["player_id", "team_id", "season_id"],
    schema: "analytics"
}
SELECT
    player_id,
    team_id,
    '2425' as season_id,
    category as position_category
FROM
    ${ref("clean_price_data")} cpd
JOIN ${ref("dim_positions")} dp
ON cpd.position = dp.position_name
${
    when(incremental(),
    `WHERE NOT EXISTS (
        SELECT 1 FROM ${self()}
        WHERE player_id = player_id
        AND team_id = team_id
        AND season_id = season_id
    )`)
}