config {
    type: "table",
    name: "clean_new_stats_rows",
    description: "New match stats grouped by player with comprehensive COALESCE",
    assertions: {
        nonNull: ["player_id"],
        uniqueKey: [["player_id", "game_id"]],
    }
}

WITH base AS (
    SELECT DISTINCT player_, game_
    FROM ${ref("new_stats_rows")}
),

stats AS (
    SELECT *
    FROM ${ref("new_stats_rows")}
),

passing AS (
    SELECT * FROM stats WHERE source_file = 'passing'
),

defending AS (
    SELECT * FROM stats WHERE source_file = 'defense'
),

passing_types AS (
    SELECT * FROM stats WHERE source_file = 'passing_types'
),

misc AS (
    SELECT * FROM stats WHERE source_file = 'misc'
),

possession AS (
    SELECT * FROM stats WHERE source_file = 'possession'
),

summary AS (
    SELECT * FROM stats WHERE source_file = 'summary'
),

goalkeeping AS (
    SELECT * FROM stats WHERE source_file = 'keepers'
)

SELECT 
    -- TODO: automate with js
    b.player_ as player_name,
    s.league_ as league_id,
    s.min_,
    s.team_,
    s.nation_ as nationality,
    s.season_ as season_id,
    s.game_ as game_id,
    REGEXP_EXTRACT(s.game_, r'(\d{4}-\d{2}-\d{2})') AS match_date,
    s.jersey_number_,
    ARRAY(
        SELECT DISTINCT pos 
        FROM UNNEST(REGEXP_EXTRACT_ALL(
            s.pos_, 
            r'([A-Z]{1,3})'
        )) pos
    ) AS positions,
    -- Calculate birth date by substructing age from match date
    DATE_SUB(
        DATE_SUB(
            PARSE_DATE('%Y-%m-%d', REGEXP_EXTRACT(s.game_, r'(\d{4}-\d{2}-\d{2})')),
            INTERVAL CAST(REGEXP_EXTRACT(s.age_, r'(\d+)') AS INT64) YEAR
        ),
        INTERVAL CAST(REGEXP_EXTRACT(s.age_, r'-(\d+)') AS INT64) DAY
    ) AS birth_date,

    COALESCE(p.performance_gls, d.performance_gls, pt.performance_gls, m.performance_gls, pos.performance_gls, s.performance_gls, g.performance_gls) AS performance_gls,
    COALESCE(p.performance_ast, d.performance_ast, pt.performance_ast, m.performance_ast, pos.performance_ast, s.performance_ast, g.performance_ast) AS performance_ast,
    COALESCE(p.performance_sh, d.performance_sh, pt.performance_sh, m.performance_sh, pos.performance_sh, s.performance_sh, g.performance_sh) AS performance_sh,
    COALESCE(p.performance_sot, d.performance_sot, pt.performance_sot, m.performance_sot, pos.performance_sot, s.performance_sot, g.performance_sot) AS performance_sot,
    COALESCE(p.performance_touches, d.performance_touches, pt.performance_touches, m.performance_touches, pos.performance_touches, s.performance_touches, g.performance_touches) AS performance_touches,
    COALESCE(p.performance_tkl, d.performance_tkl, pt.performance_tkl, m.performance_tkl, pos.performance_tkl, s.performance_tkl, g.performance_tkl) AS performance_tkl,
    COALESCE(p.performance_int, d.performance_int, pt.performance_int, m.performance_int, pos.performance_int, s.performance_int, g.performance_int) AS performance_int,
    COALESCE(p.performance_blocks, d.performance_blocks, pt.performance_blocks, m.performance_blocks, pos.performance_blocks, s.performance_blocks, g.performance_blocks) AS performance_blocks,
    COALESCE(p.expected_xg, d.expected_xg, pt.expected_xg, m.expected_xg, pos.expected_xg, s.expected_xg, g.expected_xg) AS expected_xg,
    COALESCE(p.expected_npxg, d.expected_npxg, pt.expected_npxg, m.expected_npxg, pos.expected_npxg, s.expected_npxg, g.expected_npxg) AS expected_npxg,
    COALESCE(p.expected_xag, d.expected_xag, pt.expected_xag, m.expected_xag, pos.expected_xag, s.expected_xag, g.expected_xag) AS expected_xag,
    COALESCE(p.sca_sca, d.sca_sca, pt.sca_sca, m.sca_sca, pos.sca_sca, s.sca_sca, g.sca_sca) AS sca_sca,
    COALESCE(p.sca_gca, d.sca_gca, pt.sca_gca, m.sca_gca, pos.sca_gca, s.sca_gca, g.sca_gca) AS sca_gca,
    COALESCE(p.passes_prgp, d.passes_prgp, pt.passes_prgp, m.passes_prgp, pos.passes_prgp, s.passes_prgp, g.passes_prgp) AS passes_prgp,
    COALESCE(p.carries_prgc, d.carries_prgc, pt.carries_prgc, m.carries_prgc, pos.carries_prgc, s.carries_prgc, g.carries_prgc) AS carries_prgc,
    COALESCE(p.carries_carries, d.carries_carries, pt.carries_carries, m.carries_carries, pos.carries_carries, s.carries_carries, g.carries_carries) AS carries_carries,
    COALESCE(p.`take-ons_succ`, d.`take-ons_succ`, pt.`take-ons_succ`, m.`take-ons_succ`, pos.`take-ons_succ`, s.`take-ons_succ`, g.`take-ons_succ`) AS `take-ons_succ`,
    COALESCE(p.`take-ons_att`, d.`take-ons_att`, pt.`take-ons_att`, m.`take-ons_att`, pos.`take-ons_att`, s.`take-ons_att`, g.`take-ons_att`) AS `take-ons_att`,
    COALESCE(p.game_id_, d.game_id_, pt.game_id_, m.game_id_, pos.game_id_, s.game_id_, g.game_id_) AS game_id_,
    COALESCE(p.source_file, d.source_file, pt.source_file, m.source_file, pos.source_file, s.source_file, g.source_file) AS source_file,
    COALESCE(p.ingestion_timestamp, d.ingestion_timestamp, pt.ingestion_timestamp, m.ingestion_timestamp, pos.ingestion_timestamp, s.ingestion_timestamp, g.ingestion_timestamp) AS ingestion_timestamp,
    COALESCE(p.touches_def_pen, d.touches_def_pen, pt.touches_def_pen, m.touches_def_pen, pos.touches_def_pen, s.touches_def_pen, g.touches_def_pen) AS touches_def_pen,
    COALESCE(p.touches_def_3rd, d.touches_def_3rd, pt.touches_def_3rd, m.touches_def_3rd, pos.touches_def_3rd, s.touches_def_3rd, g.touches_def_3rd) AS touches_def_3rd,
    COALESCE(p.touches_mid_3rd, d.touches_mid_3rd, pt.touches_mid_3rd, m.touches_mid_3rd, pos.touches_mid_3rd, s.touches_mid_3rd, g.touches_mid_3rd) AS touches_mid_3rd,
    COALESCE(p.touches_att_3rd, d.touches_att_3rd, pt.touches_att_3rd, m.touches_att_3rd, pos.touches_att_3rd, s.touches_att_3rd, g.touches_att_3rd) AS touches_att_3rd,
    COALESCE(p.touches_att_pen, d.touches_att_pen, pt.touches_att_pen, m.touches_att_pen, pos.touches_att_pen, s.touches_att_pen, g.touches_att_pen) AS touches_att_pen,
    COALESCE(p.touches_live, d.touches_live, pt.touches_live, m.touches_live, pos.touches_live, s.touches_live, g.touches_live) AS touches_live,
    COALESCE(p.`take-ons_succ%`, d.`take-ons_succ%`, pt.`take-ons_succ%`, m.`take-ons_succ%`, pos.`take-ons_succ%`, s.`take-ons_succ%`, g.`take-ons_succ%`) AS `take-ons_succ%`,
    COALESCE(p.carries_totdist, d.carries_totdist, pt.carries_totdist, m.carries_totdist, pos.carries_totdist, s.carries_totdist, g.carries_totdist) AS carries_totdist,
    COALESCE(p.carries_prgdist, d.carries_prgdist, pt.carries_prgdist, m.carries_prgdist, pos.carries_prgdist, s.carries_prgdist, g.carries_prgdist) AS carries_prgdist,
    COALESCE(p.receiving_rec, d.receiving_rec, pt.receiving_rec, m.receiving_rec, pos.receiving_rec, s.receiving_rec, g.receiving_rec) AS receiving_rec,
    COALESCE(p.receiving_prgr, d.receiving_prgr, pt.receiving_prgr, m.receiving_prgr, pos.receiving_prgr, s.receiving_prgr, g.receiving_prgr) AS receiving_prgr,
    COALESCE(p.att_, d.att_, pt.att_, m.att_, pos.att_, s.att_, g.att_) AS att_,
    COALESCE(p.pass_types_live, d.pass_types_live, pt.pass_types_live, m.pass_types_live, pos.pass_types_live, s.pass_types_live, g.pass_types_live) AS pass_types_live,
    COALESCE(p.pass_types_dead, d.pass_types_dead, pt.pass_types_dead, m.pass_types_dead, pos.pass_types_dead, s.pass_types_dead, g.pass_types_dead) AS pass_types_dead,
    COALESCE(p.pass_types_fk, d.pass_types_fk, pt.pass_types_fk, m.pass_types_fk, pos.pass_types_fk, s.pass_types_fk, g.pass_types_fk) AS pass_types_fk,
    COALESCE(p.pass_types_tb, d.pass_types_tb, pt.pass_types_tb, m.pass_types_tb, pos.pass_types_tb, s.pass_types_tb, g.pass_types_tb) AS pass_types_tb,
    COALESCE(p.pass_types_sw, d.pass_types_sw, pt.pass_types_sw, m.pass_types_sw, pos.pass_types_sw, s.pass_types_sw, g.pass_types_sw) AS pass_types_sw,
    COALESCE(p.pass_types_crs, d.pass_types_crs, pt.pass_types_crs, m.pass_types_crs, pos.pass_types_crs, s.pass_types_crs, g.pass_types_crs) AS pass_types_crs,
    COALESCE(p.pass_types_ti, d.pass_types_ti, pt.pass_types_ti, m.pass_types_ti, pos.pass_types_ti, s.pass_types_ti, g.pass_types_ti) AS pass_types_ti,
    COALESCE(p.pass_types_ck, d.pass_types_ck, pt.pass_types_ck, m.pass_types_ck, pos.pass_types_ck, s.pass_types_ck, g.pass_types_ck) AS pass_types_ck,
    COALESCE(p.corner_kicks_in, d.corner_kicks_in, pt.corner_kicks_in, m.corner_kicks_in, pos.corner_kicks_in, s.corner_kicks_in, g.corner_kicks_in) AS corner_kicks_in,
    COALESCE(p.corner_kicks_out, d.corner_kicks_out, pt.corner_kicks_out, m.corner_kicks_out, pos.corner_kicks_out, s.corner_kicks_out, g.corner_kicks_out) AS corner_kicks_out,
    COALESCE(p.outcomes_cmp, d.outcomes_cmp, pt.outcomes_cmp, m.outcomes_cmp, pos.outcomes_cmp, s.outcomes_cmp, g.outcomes_cmp) AS outcomes_cmp,
    COALESCE(p.outcomes_off, d.outcomes_off, pt.outcomes_off, m.outcomes_off, pos.outcomes_off, s.outcomes_off, g.outcomes_off) AS outcomes_off,
    COALESCE(p.outcomes_blocks, d.outcomes_blocks, pt.outcomes_blocks, m.outcomes_blocks, pos.outcomes_blocks, s.outcomes_blocks, g.outcomes_blocks) AS outcomes_blocks,
    COALESCE(p.performance_crdy, d.performance_crdy, pt.performance_crdy, m.performance_crdy, pos.performance_crdy, s.performance_crdy, g.performance_crdy) AS performance_crdy,
    COALESCE(p.performance_crdr, d.performance_crdr, pt.performance_crdr, m.performance_crdr, pos.performance_crdr, s.performance_crdr, g.performance_crdr) AS performance_crdr,
    COALESCE(p.performance_2crdy, d.performance_2crdy, pt.performance_2crdy, m.performance_2crdy, pos.performance_2crdy, s.performance_2crdy, g.performance_2crdy) AS performance_2crdy,
    COALESCE(p.performance_fls, d.performance_fls, pt.performance_fls, m.performance_fls, pos.performance_fls, s.performance_fls, g.performance_fls) AS performance_fls,
    COALESCE(p.performance_fld, d.performance_fld, pt.performance_fld, m.performance_fld, pos.performance_fld, s.performance_fld, g.performance_fld) AS performance_fld,
    COALESCE(p.performance_off, d.performance_off, pt.performance_off, m.performance_off, pos.performance_off, s.performance_off, g.performance_off) AS performance_off,
    COALESCE(p.performance_crs, d.performance_crs, pt.performance_crs, m.performance_crs, pos.performance_crs, s.performance_crs, g.performance_crs) AS performance_crs,
    COALESCE(p.performance_tklw, d.performance_tklw, pt.performance_tklw, m.performance_tklw, pos.performance_tklw, s.performance_tklw, g.performance_tklw) AS performance_tklw,
    COALESCE(p.performance_pkwon, d.performance_pkwon, pt.performance_pkwon, m.performance_pkwon, pos.performance_pkwon, s.performance_pkwon, g.performance_pkwon) AS performance_pkwon,
    COALESCE(p.performance_pkcon, d.performance_pkcon, pt.performance_pkcon, m.performance_pkcon, pos.performance_pkcon, s.performance_pkcon, g.performance_pkcon) AS performance_pkcon,
    COALESCE(p.performance_og, d.performance_og, pt.performance_og, m.performance_og, pos.performance_og, s.performance_og, g.performance_og) AS performance_og,
    COALESCE(p.performance_recov, d.performance_recov, pt.performance_recov, m.performance_recov, pos.performance_recov, s.performance_recov, g.performance_recov) AS performance_recov,
    COALESCE(p.aerial_duels_won, d.aerial_duels_won, pt.aerial_duels_won, m.aerial_duels_won, pos.aerial_duels_won, s.aerial_duels_won, g.aerial_duels_won) AS aerial_duels_won,
    COALESCE(p.aerial_duels_lost, d.aerial_duels_lost, pt.aerial_duels_lost, m.aerial_duels_lost, pos.aerial_duels_lost, s.aerial_duels_lost, g.aerial_duels_lost) AS aerial_duels_lost,
    COALESCE(p.`aerial_duels_won%`, d.`aerial_duels_won%`, pt.`aerial_duels_won%`, m.`aerial_duels_won%`, pos.`aerial_duels_won%`, s.`aerial_duels_won%`, g.`aerial_duels_won%`) AS `aerial_duels_won%`,
    COALESCE(p.tackles_tkl, d.tackles_tkl, pt.tackles_tkl, m.tackles_tkl, pos.tackles_tkl, s.tackles_tkl, g.tackles_tkl) AS tackles_tkl,
    COALESCE(p.tackles_tklw, d.tackles_tklw, pt.tackles_tklw, m.tackles_tklw, pos.tackles_tklw, s.tackles_tklw, g.tackles_tklw) AS tackles_tklw,
    COALESCE(p.tackles_def_3rd, d.tackles_def_3rd, pt.tackles_def_3rd, m.tackles_def_3rd, pos.tackles_def_3rd, s.tackles_def_3rd, g.tackles_def_3rd) AS tackles_def_3rd,
    COALESCE(p.tackles_mid_3rd, d.tackles_mid_3rd, pt.tackles_mid_3rd, m.tackles_mid_3rd, pos.tackles_mid_3rd, s.tackles_mid_3rd, g.tackles_mid_3rd) AS tackles_mid_3rd,
    COALESCE(p.tackles_att_3rd, d.tackles_att_3rd, pt.tackles_att_3rd, m.tackles_att_3rd, pos.tackles_att_3rd, s.tackles_att_3rd, g.tackles_att_3rd) AS tackles_att_3rd,
    COALESCE(p.challenges_tkl, d.challenges_tkl, pt.challenges_tkl, m.challenges_tkl, pos.challenges_tkl, s.challenges_tkl, g.challenges_tkl) AS challenges_tkl,
    COALESCE(p.challenges_att, d.challenges_att, pt.challenges_att, m.challenges_att, pos.challenges_att, s.challenges_att, g.challenges_att) AS challenges_att,
    COALESCE(p.`challenges_tkl%`, d.`challenges_tkl%`, pt.`challenges_tkl%`, m.`challenges_tkl%`, pos.`challenges_tkl%`, s.`challenges_tkl%`, g.`challenges_tkl%`) AS `challenges_tkl%`,
    COALESCE(p.blocks_blocks, d.blocks_blocks, pt.blocks_blocks, m.blocks_blocks, pos.blocks_blocks, s.blocks_blocks, g.blocks_blocks) AS blocks_blocks,
    COALESCE(p.blocks_sh, d.blocks_sh, pt.blocks_sh, m.blocks_sh, pos.blocks_sh, s.blocks_sh, g.blocks_sh) AS blocks_sh,
    COALESCE(p.blocks_pass, d.blocks_pass, pt.blocks_pass, m.blocks_pass, pos.blocks_pass, s.blocks_pass, g.blocks_pass) AS blocks_pass,
    COALESCE(p.int_, d.int_, pt.int_, m.int_, pos.int_, s.int_, g.int_) AS int_,
    COALESCE(p.`tkl+int_`, d.`tkl+int_`, pt.`tkl+int_`, m.`tkl+int_`, pos.`tkl+int_`, s.`tkl+int_`, g.`tkl+int_`) AS `tkl+int_`,
    COALESCE(p.clr_, d.clr_, pt.clr_, m.clr_, pos.clr_, s.clr_, g.clr_) AS clr_,
    COALESCE(p.err_, d.err_, pt.err_, m.err_, pos.err_, s.err_, g.err_) AS err_,
    COALESCE(p.nation_, d.nation_, pt.nation_, m.nation_, pos.nation_, s.nation_, g.nation_) AS nation_,
    COALESCE(p.shot_stopping_sota, d.shot_stopping_sota, pt.shot_stopping_sota, m.shot_stopping_sota, pos.shot_stopping_sota, s.shot_stopping_sota, g.shot_stopping_sota) AS shot_stopping_sota,
    COALESCE(p.shot_stopping_ga, d.shot_stopping_ga, pt.shot_stopping_ga, m.shot_stopping_ga, pos.shot_stopping_ga, s.shot_stopping_ga, g.shot_stopping_ga) AS shot_stopping_ga,
    COALESCE(p.shot_stopping_saves, d.shot_stopping_saves, pt.shot_stopping_saves, m.shot_stopping_saves, pos.shot_stopping_saves, s.shot_stopping_saves, g.shot_stopping_saves) AS shot_stopping_saves,
    COALESCE(p.`shot_stopping_save%`, d.`shot_stopping_save%`, pt.`shot_stopping_save%`, m.`shot_stopping_save%`, pos.`shot_stopping_save%`, s.`shot_stopping_save%`, g.`shot_stopping_save%`) AS `shot_stopping_save%`,
    COALESCE(p.shot_stopping_psxg, d.shot_stopping_psxg, pt.shot_stopping_psxg, m.shot_stopping_psxg, pos.shot_stopping_psxg, s.shot_stopping_psxg, g.shot_stopping_psxg) AS shot_stopping_psxg,
    COALESCE(p.launched_cmp, d.launched_cmp, pt.launched_cmp, m.launched_cmp, pos.launched_cmp, s.launched_cmp, g.launched_cmp) AS launched_cmp,
    COALESCE(p.launched_att, d.launched_att, pt.launched_att, m.launched_att, pos.launched_att, s.launched_att, g.launched_att) AS launched_att,
    COALESCE(p.`launched_cmp%`, d.`launched_cmp%`, pt.`launched_cmp%`, m.`launched_cmp%`, pos.`launched_cmp%`, s.`launched_cmp%`, g.`launched_cmp%`) AS `launched_cmp%`,
    COALESCE(p.`goal_kicks_launch%`, d.`goal_kicks_launch%`, pt.`goal_kicks_launch%`, m.`goal_kicks_launch%`, pos.`goal_kicks_launch%`, s.`goal_kicks_launch%`, g.`goal_kicks_launch%`) AS `goal_kicks_launch%`,
    COALESCE(p.crosses_opp, d.crosses_opp, pt.crosses_opp, m.crosses_opp, pos.crosses_opp, s.crosses_opp, g.crosses_opp) AS crosses_opp,
    COALESCE(p.crosses_stp, d.crosses_stp, pt.crosses_stp, m.crosses_stp, pos.crosses_stp, s.crosses_stp, g.crosses_stp) AS crosses_stp,
    COALESCE(p.`crosses_stp%`, d.`crosses_stp%`, pt.`crosses_stp%`, m.`crosses_stp%`, pos.`crosses_stp%`, s.`crosses_stp%`, g.`crosses_stp%`) AS `crosses_stp%`,
    COALESCE(p.`sweeper_#opa`, d.`sweeper_#opa`, pt.`sweeper_#opa`, m.`sweeper_#opa`, pos.`sweeper_#opa`, s.`sweeper_#opa`, g.`sweeper_#opa`) AS `sweeper_#opa`,
    COALESCE(p.sweeper_avgdist, d.sweeper_avgdist, pt.sweeper_avgdist, m.sweeper_avgdist, pos.sweeper_avgdist, s.sweeper_avgdist, g.sweeper_avgdist) AS sweeper_avgdist,
    COALESCE(p.total_cmp, d.total_cmp, pt.total_cmp, m.total_cmp, pos.total_cmp, s.total_cmp, g.total_cmp) AS total_cmp,
    COALESCE(p.total_att, d.total_att, pt.total_att, m.total_att, pos.total_att, s.total_att, g.total_att) AS total_att,
    COALESCE(p.`total_cmp%`, d.`total_cmp%`, pt.`total_cmp%`, m.`total_cmp%`, pos.`total_cmp%`, s.`total_cmp%`, g.`total_cmp%`) AS `total_cmp%`,
    COALESCE(p.`short_cmp%`, d.`short_cmp%`, pt.`short_cmp%`, m.`short_cmp%`, pos.`short_cmp%`, s.`short_cmp%`, g.`short_cmp%`) AS `short_cmp%`,
    COALESCE(p.`medium_cmp%`, d.`medium_cmp%`, pt.`medium_cmp%`, m.`medium_cmp%`, pos.`medium_cmp%`, s.`medium_cmp%`, g.`medium_cmp%`) AS `medium_cmp%`,
    COALESCE(p.long_cmp, d.long_cmp, pt.long_cmp, m.long_cmp, pos.long_cmp, s.long_cmp, g.long_cmp) AS long_cmp,
    COALESCE(p.long_att, d.long_att, pt.long_att, m.long_att, pos.long_att, s.long_att, g.long_att) AS long_att,
    COALESCE(p.`long_cmp%`, d.`long_cmp%`, pt.`long_cmp%`, m.`long_cmp%`, pos.`long_cmp%`, s.`long_cmp%`, g.`long_cmp%`) AS `long_cmp%`,
    COALESCE(p.ast_, d.ast_, pt.ast_, m.ast_, pos.ast_, s.ast_, g.ast_) AS ast_,
    COALESCE(p.xag_, d.xag_, pt.xag_, m.xag_, pos.xag_, s.xag_, g.xag_) AS xag_,
    COALESCE(p.xa_, d.xa_, pt.xa_, m.xa_, pos.xa_, s.xa_, g.xa_) AS xa_,
    COALESCE(p.kp_, d.kp_, pt.kp_, m.kp_, pos.kp_, s.kp_, g.kp_) AS kp_,
    COALESCE(p.`1_3_`, d.`1_3_`, pt.`1_3_`, m.`1_3_`, pos.`1_3_`, s.`1_3_`, g.`1_3_`) AS `1_3_`,
    COALESCE(p.ppa_, d.ppa_, pt.ppa_, m.ppa_, pos.ppa_, s.ppa_, g.ppa_) AS ppa_,
    COALESCE(p.crspa_, d.crspa_, pt.crspa_, m.crspa_, pos.crspa_, s.crspa_, g.crspa_) AS crspa_,
    COALESCE(p.prgp_, d.prgp_, pt.prgp_, m.prgp_, pos.prgp_, s.prgp_, g.prgp_) AS prgp_

FROM base b
LEFT JOIN passing p ON b.player_ = p.player_ and b.game_ = p.game_
LEFT JOIN defending d ON b.player_ = d.player_ and b.game_ = d.game_
LEFT JOIN passing_types pt ON b.player_ = pt.player_ and b.game_ = pt.game_
LEFT JOIN misc m ON b.player_ = m.player_ and b.game_ = m.game_
LEFT JOIN possession pos ON b.player_ = pos.player_ and b.game_ = pos.game_
LEFT JOIN summary s ON b.player_ = s.player_ and b.game_ = s.game_
LEFT JOIN goalkeeping g ON b.player_ = g.player_ and b.game_ = g.game_