config {
    type: "incremental",
    name: "dim_players",
    description: "Dimension table for players",
    uniqueKey: ["player_id"],
    schema: "analytics"
}
SELECT 
    player_id,
    player_name,
    nationality,
    birth_date,
    current_timestamp() as last_updated
FROM 
    ${ref("clean_price_data")}

${when(incremental(), `
WHERE
player_id NOT IN (
    SELECT player_id 
    FROM ${self()}
)`, `
-- On full refresh, include all players
`)}