config {
    type: "incremental",
    name: "radar_metrics_centerbacks",
    description: "Fact table for centerbacks statistics",
    uniqueKey: ["player_id", "game_id"],
    schema: "analytics"
}

WITH new_match_stats AS
(
    SELECT
        player_id,
        game_id,
        season_id,
        min_ as minutes_played,
        -- 1)aerial duels won %
        `aerial_duels_won%` as aerial_duels_won_rate,
        -- 2)clearences per 90
        clr_ as clearences,
        -- 3)Interceptions Per 90
        int_ as interceptions,
        -- 4) Blocks Per 90
        blocks_blocks as blocks,
        -- 5) Progressive Passes Per 90 
        prgp_ as progressive_passes,
        -- 6) Long Pass Completion % 
        `long_cmp%` as long_pass_completion_rate,
        -- 7) Defensive Aggression Index. Formula: (Tkl + Int) / (Blocks + Clr)
        ROUND(SAFE_DIVIDE((tackles_tkl + int_), (blocks_blocks + clr_)), 3) as defensive_aggression_index

    FROM
        ${ref("players_joined")}
    WHERE
        'CB' IN UNNEST(positions)
)

SELECT 
    *
FROM
    new_match_stats
