config {
    type: "view",
    name: "radar_metrics_midfielders_career",
    description: "Career averages for midfielders statistics",
    schema: "analytics",
    tags:["radar", "career"]
}

WITH career_stats AS (
    SELECT 
        player_id,
        SUM(minutes_played) AS total_minutes_played,
        
        -- Weighted metrics per 90
        SUM(progressive_passes * minutes_played) / SUM(minutes_played) * 90 AS avg_progressive_passes,
        SUM(progressive_carries * minutes_played) / SUM(minutes_played) * 90 AS avg_progressive_carries,
        SUM(shot_creating_actions * minutes_played) / SUM(minutes_played) * 90 AS avg_shot_creating_actions,
        SUM(defensive_work * minutes_played) / SUM(minutes_played) * 90 AS avg_defensive_work,
        SUM(final_third_passes * minutes_played) / SUM(minutes_played) * 90 AS avg_final_third_passes,
        SUM(goal_creating_actions * minutes_played) / SUM(minutes_played) * 90 AS avg_goal_creating_actions,

        -- Straight average for pass completion %
        AVG(pass_completion_rate) AS avg_pass_completion_rate

    FROM 
        ${ref("radar_metrics_midfielders")}
    GROUP BY 
        player_id
),

percentiles AS (
    SELECT
        player_id,
        PERCENT_RANK() OVER(ORDER BY avg_progressive_passes) AS progressive_passes_percentile,
        PERCENT_RANK() OVER(ORDER BY avg_progressive_carries) AS progressive_carries_percentile,
        PERCENT_RANK() OVER(ORDER BY avg_shot_creating_actions) AS shot_creating_actions_percentile,
        PERCENT_RANK() OVER(ORDER BY avg_defensive_work) AS defensive_work_percentile,
        PERCENT_RANK() OVER(ORDER BY avg_final_third_passes) AS final_third_passes_percentile,
        PERCENT_RANK() OVER(ORDER BY avg_goal_creating_actions) AS goal_creating_actions_percentile,
        PERCENT_RANK() OVER(ORDER BY avg_pass_completion_rate) AS pass_completion_rate_percentile
    FROM 
        career_stats
)

SELECT 
    c.player_id,
    c.total_minutes_played,
    c.avg_progressive_passes,
    c.avg_progressive_carries,
    c.avg_shot_creating_actions,
    c.avg_defensive_work,
    c.avg_final_third_passes,
    c.avg_goal_creating_actions,
    c.avg_pass_completion_rate,
    
    p.progressive_passes_percentile,
    p.progressive_carries_percentile,
    p.shot_creating_actions_percentile,
    p.defensive_work_percentile,
    p.final_third_passes_percentile,
    p.goal_creating_actions_percentile,
    p.pass_completion_rate_percentile

FROM 
    career_stats c
JOIN 
    percentiles p
ON 
    c.player_id = p.player_id
